-- 1. Tabela BAZY_FARB
CREATE TABLE BAZY_FARB (
    BAZA_ID NUMBER NOT NULL,
    NAZWA VARCHAR2(100) NOT NULL,
    POJEMNOSC_LITRY NUMBER(10,2) NOT NULL,
    KOSZT_ZA_LITR NUMBER(10,2) NOT NULL,
    TYP_FARB VARCHAR2(50) NOT NULL,
    DATA_DOSTAWY DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BAZY_FARB PRIMARY KEY (BAZA_ID),
    CONSTRAINT UN_BAZY_FARB_NAZWA UNIQUE (NAZWA)
);

-- 2. Tabela KLIENCI
CREATE TABLE KLIENCI (
    KLIENT_ID NUMBER NOT NULL,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    TELEFON VARCHAR2(15),
    DATA_REJESTRACJI DATE DEFAULT SYSDATE,
    MIASTO VARCHAR2(50) NOT NULL,
    ULICA VARCHAR2(100) NOT NULL,
    KOD_POCZTOWY VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_KLIENCI PRIMARY KEY (KLIENT_ID),
    CONSTRAINT UN_KLIENCI_EMAIL UNIQUE (EMAIL)
);

-- 3. Tabela PRACOWNICY
CREATE TABLE PRACOWNICY (
    PRACOWNIK_ID NUMBER NOT NULL,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    STANOWISKO VARCHAR2(50) NOT NULL,
    DATA_ZATRUDNIENIA DATE DEFAULT SYSDATE,
    AKTYWNY CHAR(1) DEFAULT 'Y',
    OSTATNIE_LOGOWANIE TIMESTAMP,
    CONSTRAINT PK_PRACOWNICY PRIMARY KEY (PRACOWNIK_ID),
    CONSTRAINT UN_PRACOWNICY_EMAIL UNIQUE (EMAIL)
);

-- 4. Tabela PIGMENTY
CREATE TABLE PIGMENTY (
    PIGMENT_ID NUMBER NOT NULL,
    NAZWA VARCHAR2(100) NOT NULL,
    KOD_KOLORU VARCHAR2(30) NOT NULL,
    KOLOR_HEX VARCHAR2(10) NOT NULL,
    DATA_DODANIA DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PIGMENTY PRIMARY KEY (PIGMENT_ID),
    CONSTRAINT UN_PIGMENTY_NAZWA UNIQUE (NAZWA),
    CONSTRAINT UN_PIGMENTY_KOD UNIQUE (KOD_KOLORU)
);

-- 5. Tabela RECEPTURY
CREATE TABLE RECEPTURY (
    RECEPTURA_ID NUMBER NOT NULL,
    NAZWA VARCHAR2(100) NOT NULL,
    KOD_KOLORU VARCHAR2(20) NOT NULL,
    OPIS VARCHAR2(500),
    UTWORZONO DATE DEFAULT SYSDATE,
    BAZA_ID NUMBER NOT NULL,
    ILOSC_BAZY_LITRY NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_RECEPTURY PRIMARY KEY (RECEPTURA_ID),
    CONSTRAINT UN_RECEPTURY_NAZWA UNIQUE (NAZWA),
    CONSTRAINT UN_RECEPTURY_KOD UNIQUE (KOD_KOLORU),
    CONSTRAINT FK_RECEPTURY_BAZA FOREIGN KEY (BAZA_ID) 
        REFERENCES BAZY_FARB(BAZA_ID)
);

-- 6. Tabela RECEPTURA_PIGMENTY
CREATE TABLE RECEPTURA_PIGMENTY (
    RECEPTURA_PIGMENTY_ID NUMBER NOT NULL,
    RECEPTURA_ID NUMBER NOT NULL,
    PIGMENT_ID NUMBER NOT NULL,
    ILOSC_GRAMY NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_RECEPTURA_PIGMENTY PRIMARY KEY (RECEPTURA_PIGMENTY_ID),
    CONSTRAINT UQ_RECEPTURA_PIGMENT UNIQUE (RECEPTURA_ID, PIGMENT_ID),
    CONSTRAINT FK_REC_PIG_REC FOREIGN KEY (RECEPTURA_ID) REFERENCES RECEPTURY(RECEPTURA_ID),
    CONSTRAINT FK_REC_PIG_PIG FOREIGN KEY (PIGMENT_ID) REFERENCES PIGMENTY(PIGMENT_ID)
);

-- 7. Tabela ZAMOWIENIA
CREATE TABLE ZAMOWIENIA (
    ZAMOWIENIE_ID NUMBER NOT NULL,
    NUMER_ZAMOWIENIA VARCHAR2(20) NOT NULL,
    KLIENT_ID NUMBER NOT NULL,
    RECEPTURA_ID NUMBER NOT NULL,
    PRACOWNIK_ID NUMBER NOT NULL,
    DATA_ZAMOWIENIA DATE DEFAULT SYSDATE,
    ILOSC_LITRY NUMBER(10,2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'Oczekujące' NOT NULL,
    CONSTRAINT PK_ZAMOWIENIA PRIMARY KEY (ZAMOWIENIE_ID),
    CONSTRAINT UN_ZAMOWIENIA_NUMER UNIQUE (NUMER_ZAMOWIENIA),
    CONSTRAINT FK_ZAM_KLIENT FOREIGN KEY (KLIENT_ID) REFERENCES KLIENCI(KLIENT_ID),
    CONSTRAINT FK_ZAM_REC FOREIGN KEY (RECEPTURA_ID) REFERENCES RECEPTURY(RECEPTURA_ID),
    CONSTRAINT FK_ZAM_PRAC FOREIGN KEY (PRACOWNIK_ID) REFERENCES PRACOWNICY(PRACOWNIK_ID)
);

-- 8. Indeksy
CREATE INDEX IDX_KLIENCI_NAZWISKO ON KLIENCI(NAZWISKO);
CREATE INDEX IDX_ZAMOWIENIA_PRACOWNIK ON ZAMOWIENIA(PRACOWNIK_ID);
CREATE INDEX IDX_ZAMOWIENIA_KLIENT ON ZAMOWIENIA(KLIENT_ID);
CREATE INDEX IDX_RECEPTURY_BAZA ON RECEPTURY(BAZA_ID);
