-- UPDATE
UPDATE ZAMOWIENIA
SET STATUS = 'Zrealizowane'
WHERE NUMER_ZAMOWIENIA = 'ZAM-2025-1001';

-- DELETE
DELETE FROM PIGMENTY
WHERE NAZWA = 'Pigment 1'
AND PIGMENT_ID NOT IN (SELECT PIGMENT_ID FROM RECEPTURA_PIGMENTY);

-- SELECT
SELECT
    z.NUMER_ZAMOWIENIA,
    k.NAZWISKO AS KLIENT,
    r.NAZWA AS KOLOR,
    z.STATUS
FROM ZAMOWIENIA z
JOIN KLIENCI k ON z.KLIENT_ID = k.KLIENT_ID
JOIN RECEPTURY r ON z.RECEPTURA_ID = r.RECEPTURA_ID
WHERE z.STATUS = 'Zrealizowane';

-- Raport 1
SELECT
    z.NUMER_ZAMOWIENIA,
    z.DATA_ZAMOWIENIA,
    k.IMIE || ' ' || k.NAZWISKO AS KLIENT,
    z.ILOSC_LITRY,
    z.STATUS
FROM
    ZAMOWIENIA z
    JOIN KLIENCI k ON z.KLIENT_ID = k.KLIENT_ID
    JOIN RECEPTURY r ON z.RECEPTURA_ID = r.RECEPTURA_ID
ORDER BY
    z.DATA_ZAMOWIENIA DESC;
    
-- Raport 2
SELECT
    p.NAZWISKO,
    p.IMIE,
    p.STANOWISKO,
    COUNT(z.ZAMOWIENIE_ID) AS LICZBA_ZREALIZOWANYCH_ZAMOWIEN
FROM
    PRACOWNICY p
    LEFT JOIN ZAMOWIENIA z ON p.PRACOWNIK_ID = z.PRACOWNIK_ID
GROUP BY
    p.NAZWISKO, p.IMIE, p.STANOWISKO
ORDER BY 
    LICZBA_ZREALIZOWANYCH_ZAMOWIEN DESC;
    
-- Raport 3
SELECT 
    r.NAZWA AS RECEPTURA,
    b.KOSZT_ZA_LITR AS KOSZT_BAZY,
    SUM(z.ILOSC_LITRY) AS TOTAL_SPRZEDANO,
    ROUND(SUM(z.ILOSC_LITRY * b.KOSZT_ZA_LITR), 2) AS SUMARYCZNY_KOSZT_PRODUKCJI
FROM RECEPTURY r
JOIN BAZY_FARB b ON r.BAZA_ID = b.BAZA_ID
JOIN ZAMOWIENIA z ON r.RECEPTURA_ID = z.RECEPTURA_ID
WHERE z.STATUS = 'Zrealizowane'
GROUP BY r.NAZWA, b.KOSZT_ZA_LITR
ORDER BY TOTAL_SPRZEDANO DESC;
    
-- Raport 4
SELECT 
    p.IMIE || ' ' || p.NAZWISKO AS PRACOWNIK,
    p.STANOWISKO,
    COUNT(z.ZAMOWIENIE_ID) AS LICZBA_ZAMOWIEN,
    COUNT(DISTINCT z.KLIENT_ID) AS UNIKALNI_KLIENCI,
    ROUND(AVG(z.ILOSC_LITRY), 2) AS SREDNIA_ILOSC_LITROW
FROM PRACOWNICY p
LEFT JOIN ZAMOWIENIA z ON p.PRACOWNIK_ID = z.PRACOWNIK_ID
GROUP BY p.PRACOWNIK_ID, p.IMIE, p.NAZWISKO, p.STANOWISKO
HAVING COUNT(z.ZAMOWIENIE_ID) > 0
ORDER BY LICZBA_ZAMOWIEN DESC;

-- Raport 5
SELECT 
    b.NAZWA AS BAZA,
    b.POJEMNOSC_LITRY AS STAN_POCZATKOWY,
    NVL(SUM(z.ILOSC_LITRY), 0) AS ZAREZERWOWANE_LITRY,
    b.POJEMNOSC_LITRY - NVL(SUM(z.ILOSC_LITRY), 0) AS PRZEWIDYWANY_STAN,
    CASE 
        WHEN (b.POJEMNOSC_LITRY - SUM(z.ILOSC_LITRY)) < 10 THEN 'KRYTYCZNY - ZAMÓW DOSTAWĘ!'
        WHEN (b.POJEMNOSC_LITRY - SUM(z.ILOSC_LITRY)) < 50 THEN 'NISKI'
        ELSE 'OK'
    END AS STATUS_MAGAZYNU
FROM BAZY_FARB b
LEFT JOIN RECEPTURY r ON b.BAZA_ID = r.BAZA_ID
LEFT JOIN ZAMOWIENIA z ON r.RECEPTURA_ID = z.RECEPTURA_ID AND z.STATUS IN ('Oczekujące', 'W trakcie')
GROUP BY b.NAZWA, b.POJEMNOSC_LITRY
ORDER BY PRZEWIDYWANY_STAN ASC;

-- Raport 6
SELECT 
    p.NAZWA AS PIGMENT,
    p.KOD_KOLORU,
    COUNT(DISTINCT r.RECEPTURA_ID) AS LICZBA_RECEPTUR,
    ROUND(SUM(z.ILOSC_LITRY * rp.ILOSC_GRAMY), 2) AS ZUZYCIE_CALKOWITE_GRAMY
FROM PIGMENTY p
JOIN RECEPTURA_PIGMENTY rp ON p.PIGMENT_ID = rp.PIGMENT_ID
JOIN RECEPTURY r ON rp.RECEPTURA_ID = r.RECEPTURA_ID
JOIN ZAMOWIENIA z ON r.RECEPTURA_ID = z.RECEPTURA_ID
WHERE z.STATUS = 'Zrealizowane'
GROUP BY p.NAZWA, p.KOD_KOLORU
ORDER BY ZUZYCIE_CALKOWITE_GRAMY DESC;
